from npc_generator import *

dragonborn = ancestry('dragonborn',1,['Arjhan', 'Balasar', 'Bharash', 'Donaar', 'Ghesh', 'Heskan',
                                      'Kriv', 'Medrash', 'Mehen', 'Nadarr', 'Pandjed', 'Patrin',
                                      'Rhogar', 'Shamash', 'Shedinn','Tarhun', 'Torinn'],
                      ['Akra', 'Biri', 'Daar', 'Farideh', 'Harann', 'Havilar', 'Jheri', 'Kava',
                       'Korinn', 'Mishann', 'Nala', 'Perra', 'Raiann', 'Sora', 'Surina',
                       'Thava','Uadjit'],
                      ['Thava','Uadjit','Tarhun', 'Torinn'],['d1','d2','d3'])
dwarf = ancestry('dwarf',5,['Adrik', 'Alberich', 'Baern', 'Barendd', 'Brottor', 'Bruenor',
                            'Dain', 'Darrak', 'Delg', 'Eberk', 'Einkil', 'Fargrim', 'Flint', 'Gardain',
                            'Harbek', 'Kildrak', 'Morgran', 'Orsik', 'Oskar', 'Rangrim', 'Rurik', 'Taklinn',
                            'Thoradin', 'Thorin', 'Tordek', 'Traubon', 'Travok', 'Ulfgar', 'Veit', 'Vondal'],
                 ['Amber', 'Artin', 'Audhild', 'Bardryn', 'Dagnal', 'Diesa', 'Eldeth', 'Falkrunn',
                  'Finellen', 'Gunnloda', 'Gurdis', 'Helja', 'Hlin', 'Kathra', 'Kristryd', 'Ilde',
                  'Liftrasa', 'Mardred', 'Riswynn', 'Sannl', 'Torbera', 'Torgga', 'Vistra'],
                 ['Torbera', 'Torgga', 'Vistra', 'Ulfgar', 'Veit', 'Vondal'],['d1','d2','d3'])
elf = ancestry('elf',2,['Adran', 'Aelar', 'Aramil', 'Arannis', 'Aust', 'Beiro', 'Berrian', 'Carric',
                        'Enialis', 'Erdan', 'Erevan', 'Galinndan', 'Hadarai', 'Heian', 'Himo',
                        'Immeral', 'Ivellios', 'Laucian', 'Mindartis', 'Paelias', 'Peren', 'Quarion',
                        'Riardon', 'Rolen', 'Soveliss', 'Thamior', 'Tharivol', 'Theren', 'Varis'],
               ['Adrie', 'Althaea', 'Anastrianna', 'Andraste', 'Antinua', 'Bethrynna',
                'Birel', 'Caelynn', 'Drusilia', 'Enna', 'Felosial', 'Ielenia', 'Jelenneth', 'Keyleth',
                'Leshanna', 'Lia', 'Meriele', 'Mialee', 'Naivara', 'Quelenna', 'Quillathe', 'Sariel',
                'Shanairra', 'Shava', 'Silaqui', 'Theirastra', 'Thia', 'Vadania', 'Valanthe',
                'Xanaphia']
               ,['Tharivol', 'Theren',  'Varis', 'Vadania', 'Valanthe',  'Xanaphia'],['d1','d2','d3'])
gnome = ancestry('gnome',3,['Alston',
 'Alvyn',
 'Boddynock',
 'Brocc',
 'Burgell',
 'Dimble',
 'Eldon',
 'Erky',
 'Fonkin',
 'Frug',
 'Gerbo',
 'Gimble',
 'Glim',
 'Jebeddo',
 'Kellen',
 'Namfoodle',
 'Orryn',
 'Roondar',
 'Seebo',
 'Sindri',
 'Warryn',
 'Wrenn',
 'Zook']
,['Bimpnottin',
 'Breena',
 'Caramip',
 'Carlin',
 'Donella',
 'Duvamil',
 'Ella',
 'Ellyjobell',
 'Ellywick',
 'Lilli',
 'Loopmottin',
 'Lorilla',
 'Mardnab',
 'Nissa',
 'Nyx',
 'Oda',
 'Orla',
 'Roywyn',
 'Shamil',
 'Tana',
 'Waywocket',
 'Zanna']
,['Warryn',
 'Wrenn',
 'Zook',
 'Tana',
 'Waywocket',
 'Zanna'],['d1','d2','d3'])

halfelf = ancestry('half-elf',2,[],[],[],['d1','d2','d3'])
halfling = ancestry('halfling',3,['Alton','Ander', 'Cade', 'Corrin', 'Eldon',
 'Errich', 'Finnan', 'Garret', 'Lindal', 'Lyle', 'Merric', 'Milo', 'Osborn',
 'Perrin', 'Reed', 'Roscoe', 'Wellby'],
['Andry',
 'Bree',
 'Callie',
 'Cora',
 'Euphemia',
 'Jillian',
 'Kithri',
 'Lavinia',
 'Lidda',
 'Merla',
 'Nedda',
 'Paela',
 'Portia',
 'Seraphina',
 'Shaena',
 'Trym',
 'Vani',
  'Verna'],
['Perrin', 'Reed', 'Roscoe', 'Wellby','Seraphina',
 'Shaena',
 'Trym',
 'Vani',
  'Verna'],['d1','d2','d3'])
halforc = ancestry('half-orc',2,['Dench',
 'Feng',
 'Gell',
 'Henk',
 'Holg',
 'Imsh',
 'Keth',
 'Krusk',
 'Mhurren',
 'Ront',
 'Shump',
 'Thokk']
,['Baggi',
 'Emen',
 'Engong',
 'Kansif',
 'Myev',
 'Neega',
 'Ovak',
 'Ownka',
 'Shautha',
 'Sutha',
 'Vola',
 'Volen',
 'Yevelda']
,['Gell','Henk','Holg','Ovak','Emen','Vola'],['d1','d2','d3'])
human = ancestry('human',5,['Darvin', 'Dorn', 'Evendur',
 'Gorstag',
 'Grim',
 'Helm','Malark','Morn','Randal',                                                                                                                                                                                                                              
 'Stedd',                                                                                                                                                                                                                               
 'Bor',                                                                                                                                                                                                                                 
 'Fodel',                                                                                                                                                                                                                               
 'Glar',                                                                                                                                                                                                                                
 'Grigor',                                                                                                                                                                                                                              
 'Igan',                                                                                                                                                                                                                                
 'Ivor',                                                                                                                                                                                                                                
 'Kosef',                                                                                                                                                                                                                               
 'Mival',                                                                                                                                                                                                                               
 'Orel',                                                                                                                                                                                                                                
 'Pavel',                                                                                                                                                                                                                               
 'Sergor',                                                                                                                                                                                                                              
 'Ander',                                                                                                                                                                                                                               
 'Blath',
 'Bran',
 'Frath',
 'Geth',
 'Lander',
 'Luth',
 'Malcer',
 'Stor',
 'Taman',
 'Urth',
 'Aoth',
 'Bareris',
 'Ehput-Ki',
 'Kethoth',
 'Mumed',
 'Ramas',
 'So-Kehur',
 'Thazar-De',
 'Urhur',
 'Borivik',
 'Faurgar',
 'Jandar',
 'Kanithar','Madislak',
 'Ralmevik',
 'Shaumar',
 'Vladislak',
 'An',
 'Chen',
 'Chi',
 'Fai',
 'Jiang',
 'Jun',
 'Lian',
 'Long',
 'Meng',
 'On',
 'Shan',
 'Shui',
 'Wen',
 'Anton',
 'Diero',
 'Marcon',
 'Pieron',
 'Rimardo',
 'Romero',
 'Salazar',
 'Umbero'],
['Atala',                                                                                                                                                                                                                               
 'Ceidil',                                                                                                                                                                                                                              
 'Hama',                                                                                                                                                                                                                                
 'Jasmal',                                                                                                                                                                                                                              
 'Meilil',                                                                                                                                                                                                                              
 'Seipora',                                                                                                                                                                                                                             
 'Yasheira',                                                                                                                                                                                                                            
  'Zasheida',
 'Arveene',                                                                                                                                                                                                                     
 'Esvele',                                                                                                                                                                                                                              
 'Jhessail',                                                                                                                                                                                                                            
 'Kerri',                                                                                                                                                                                                                               
 'Lureene', 'Miri',
 'Rowan',
 'Shandri',
 'TesseleAlethra',
 'Kara',
 'Katernin',
 'Mara',
 'Natali',
 'Olma',
 'Tana',
  'Zora',
 'Amafrey',
 'Betha',
 'Cefrey',
 'Kethra',
 'Mara',
 'Olga',
 'Silifrey',
  'Westra',
  'Arizima',
 'Chathi',
 'Nephis',
 'Nulara',
 'Murithi',
 'Sefris',
 'Thola',
 'Umara',
  'Zolis',
 'Fyevarra',
 'Hulmarra',
 'Immith',
 'Imzel',
 'Navarra',
 'Shevarra',
 'Tammith',
  'Yuldra',
  'Bai',
  'Chao',
  'Jia',
  'Lei',
  'Mei',
  'Qiao',
  'Shui',
  'Tai',
  'Balama',
 'Dona',
 'Faila',
 'Jalana',
 'Luisa',
 'Marta',
 'Quara',
 'Selise',
  'Vonda'],

['Quara',
 'Selise',
 'Vonda',
 'Pieron',
 'Rimardo',
 'Romero',
 'Salazar',
 'Umbero'],['d1','d2','d3'])
tiefling = ancestry('tiefling',1,['Akmenos',
 'Amnon',
 'Barakas',
 'Damakos',
 'Ekemon',
 'Iados',
 'Kairon',
 'Leucis',
 'Melech',
 'Mordai',
 'Morthos',
 'Pelaios',
 'Skamos',
 'Therai',
 'Art',
 'Carrion',
 'Chant',
 'Creed',
 'Despair',
 'Excellence',
 'Fear',
 'Glory',
 'Hope',
 'Ideal',
 'Music',
 'Nowhere',
 'Open',
 'Poetry',
 'Quest',
 'Random',
 'Reverence',
 'Sorrow',
 'Temerity',
 'Torment',
 'Weary'],['Akta',
 'Anakis',
 'Bryseis',
 'Criella',
 'Damaia',
 'Ea',
 'Kallista',
 'Lerissa',
 'Makaria',
 'Nemeia',
 'Orianna',
 'Phelaia',
 'Rieta',
 'Art',
 'Carrion',
 'Chant',
 'Creed',
 'Despair',
 'Excellence',
 'Fear',
 'Glory',
 'Hope',
 'Ideal',
 'Music',
 'Nowhere',
 'Open',
 'Poetry',
 'Quest',
 'Random',
 'Reverence',
 'Sorrow',
 'Temerity',
 'Torment',
 'Weary']
,['Art',
 'Carrion',
 'Chant',
 'Creed',
 'Despair',
 'Excellence',
 'Fear',
 'Glory',
 'Hope',
 'Ideal',
 'Music',
 'Nowhere',
 'Open',
 'Poetry',
 'Quest',
 'Random',
 'Reverence',
 'Sorrow',
 'Temerity',
 'Torment',
 'Weary']
,['d1','d2','d3'])

halfelf.m_names = human.m_names + elf.m_names
halfelf.f_names = human.f_names + elf.f_names
halfelf.x_names = human.x_names + elf.x_names

ancestries = {dragonborn.ancestry:dragonborn,
              dwarf.ancestry:dwarf,
              elf.ancestry:elf,
              gnome.ancestry:gnome,
              halfelf.ancestry:halfelf,
              halfling.ancestry:halfling,
              halforc.ancestry:halforc,
              human.ancestry:human,
              tiefling.ancestry:tiefling}

ancestry_table = ancestry_table(ancestries)

appearance = ['distinctive jewelry','piercings','flamboyant clothing','formal clothes',
              'ragged clothes','pronounced scar','missing teeth','missing fingers',
              'unusual eye color', 'tattoos','birthmark','unusual skin color','bald',
              'braided beard or hair', 'unusual hair color', 'nervous eye twitch','distinctive nose',
              'distinctive posture', 'exceptionally beautiful','exceptionally ugly']
abilities = ['high strength — powerful, brawny, strong as an ox',
             'high dexterity — lithe, agile, graceful',
             'high constitution — hardy, hale, healthy',
             'high intelligence — studious, learned, inquisitive',
             'high wisdom — perceptive, spiritual, insightful',
             'high charisma — persuasive, forceful, born leader',
             'low strength — feeble, scrawny',
             'low dexterity — clumsy, fumbling',
             'low constitution — sickly, pale',
             'low intelligence — dim-witted, slow',
             'low wisdom — oblivious, absentminded',
             'low charisma — dull, boring']
talents = ['Plays a musical instrument','Speaks several languages fluently','Unbelievably lucky',
           'Perfect memory', 'Great with animals','Great with children','Great at solving puzzles',
           'Great at one game','Great at impersonations','Draws beautifully','Paints beautifully',
           'Sings beautifully','Drinks everyone under the table','Expert carpenter','Expert cook',
           'Expert dart thrower and rock skipper','Expert juggler',
           'Skilled actor and master of disguise', 'Skilled dancer', 'Knows thieves cant']
mannerisms = ['Prone to singing, whistling, or humming quietly',
              'Speaks in rhyme or some other peculiar way',
              'Particularly low or high voice',
              'Slurs words, lisps, or stutters',
              'Enunciates overly clearly',
              'Speaks loudly',
              'Whispers',
              'Uses flowery speech or long words',
              'Frequently uses the wrong word',
              'Uses colorful oaths and exclamations',
              'Makes constant jokes or puns',
              'Prone to predictions of doom',
              'Fidgets',
              'Squints',
              'Stares into the distance',
              'Chews something',
              'Paces',
              'Taps fingers',
              'Bites fingernails',
              'Twirls hair or tugs beard']
interactions = ['Argumentative',
                'Arrogant',
                'Blustering',
                'Rude',
                'Curious',
                'Friendly',
                'Honest',
                'Hot tempered',
                'Irritable',
                'Ponderous',
                'Quiet',
                'Suspicious']
ideals = ['Beauty','Domination','Charity','Greed','Greater good','Might','Life','Pain','Respect',
          'Retribution','Self-sacrifice','Slaughter','Community','Change','Fairness','Creativity',
          'Honor','Freedom','Logic','Independence','Responsibility','No limits','Tradition','Whimsy',
          'Balance','Aspiration','Knowledge','Discovery','Live and let live','Glory','Moderation',
	      'Nation','Neutrality','Redemption','People','Self-knowledge']
bonds = ['Dedicated to fulfilling a personal life goal',
         'Protective of close family members',
         'Protective of colleagues or compatriots',
         'Loyal to a benefactor, patron, or employer',
         'Captivated by a romantic interest',
         'Drawn to a special place',
         'Protective of a sentimental keepsake',
         'Protective of a valuable possession',
         'Out for revenge']
flaws = ['Forbidden love or susceptibility to romance',
         'Enjoys decadent pleasures',
         'Arrogance',
         'Envies another creature’s possessions or station',
         'Overpowering greed',
         'Prone to rage',
         'Has a powerful enemy',
         'Specific phobia',
         'Shameful or scandalous history',
         'Secret crime or misdeed',
         'Possession of forbidden lore',
         'Foolhardy bravery',]

quirk_table = quirk_table(appearance,abilities,talents,mannerisms,interactions,ideals,bonds,flaws)
